[package]
name = "numaflow"
version = "0.1.0"
edition = "2021"

[lib]
name = "numaflow"
path = "src/lib.rs"

[dependencies]
tonic = "0.9"
prost = "0.11"
prost-types = "0.11.9"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
serde = { version = "1.0.103", features = ["derive"] }
chrono = "0.4.26"
serde_json = "1.0.103"
futures-util = "0.3.28"

[build-dependencies]
tonic-build = "0.9"
